python train_base.py \
    --train_data "../data/final_preprocessed/train" \
    --val_data "data/final_preprocessed/val" \
    --test_data "data/final_preprocessed/test" \
    --epochs 10 \
    --batch_size 32 \
    --lr 0.0001 \
    --num_workers 4 \
    --num_hidden_layers 12 \
    --num_heads 12 \
    --out_dir "$PROJECT_DIR/output/slurm_run_${SLURM_JOB_ID}" \
    --create_opcode_ids